#!/usr/bin/env python3
"""Regenerate crates/cordial-runtime/src/bionic/sysconf_table.rs.

bionic and glibc each number the `_SC_*` selectors for `sysconf()` in their own
way, and they agree on almost nothing: of the 147 constants bionic defines, 145
have a different value under glibc. Passing one through untranslated does not
fail — it silently answers a different question. Roblox asks for `_SC_PAGESIZE`
(bionic 39); glibc reads 39 as `_SC_BC_STRING_MAX` and returns 1000, and the
allocator handed a non-power-of-two page size aborts during static
initialisation.

bionic's values are `#define`s and can be scraped. glibc's are an enum, so they
are obtained by compiling a probe that prints them.

Usage:
    tools/gen_sysconf_table.py path/to/bionic/libc/include
"""

import pathlib
import re
import subprocess
import sys
import tempfile

DEST = pathlib.Path(__file__).resolve().parent.parent / (
    "crates/cordial-runtime/src/bionic/sysconf_table.rs"
)


def bionic_constants(include_dir):
    pattern = re.compile(r"#define\s+(_SC_[A-Z0-9_]+)\s+(0x[0-9a-fA-F]+|\d+)")
    found = {}
    for path in pathlib.Path(include_dir).rglob("*.h"):
        for name, value in pattern.findall(path.read_text(errors="ignore")):
            found[name] = int(value, 0)
    return found


def glibc_constants(names):
    """Compile a probe, because glibc's selectors are an enum, not defines."""
    body = "\n".join(
        f'#ifdef {n}\nprintf("{n} %d\\n", (int){n});\n#endif' for n in sorted(names)
    )
    with tempfile.TemporaryDirectory() as tmp:
        src = pathlib.Path(tmp) / "probe.c"
        exe = pathlib.Path(tmp) / "probe"
        src.write_text(f"#include <unistd.h>\n#include <stdio.h>\nint main(){{\n{body}\nreturn 0;}}\n")
        subprocess.run(["cc", "-o", str(exe), str(src)], check=True)
        out = subprocess.run([str(exe)], capture_output=True, text=True, check=True).stdout
    return {n: int(v) for n, v in (line.split() for line in out.splitlines())}


def main():
    if len(sys.argv) != 2:
        print(__doc__, file=sys.stderr)
        return 2

    bionic = bionic_constants(sys.argv[1])
    if not bionic:
        print(f"no _SC_* defines found under {sys.argv[1]}", file=sys.stderr)
        return 1
    glibc = glibc_constants(bionic)

    shared = sorted(set(bionic) & set(glibc), key=lambda n: bionic[n])
    missing = sorted(set(bionic) - set(glibc))
    differing = sum(1 for n in shared if bionic[n] != glibc[n])

    lines = [
        "// Generated by tools/gen_sysconf_table.py. Do not edit.",
        "//",
        "// bionic and glibc number the _SC_* selectors independently: of the",
        f"// {len(bionic)} constants bionic defines, {differing} have a different value under glibc.",
        "// Passing one through untranslated silently answers a different question.",
        "",
        "use std::ffi::c_int;",
        "",
        '/// `(bionic value, glibc value, name)`, ordered by bionic value.',
        "pub const SYSCONF_MAP: &[(c_int, c_int, &str)] = &[",
    ]
    lines += [f'    ({bionic[n]}, {glibc[n]}, "{n}"),' for n in shared]
    lines += ["];", "", "/// bionic selectors glibc has no equivalent for.",
              "pub const UNSUPPORTED: &[(c_int, &str)] = &["]
    lines += [f'    ({bionic[n]}, "{n}"),' for n in missing]
    lines += ["];"]

    DEST.write_text("\n".join(lines) + "\n")
    print(f"{len(shared)} mapped ({differing} differing), {len(missing)} unsupported -> {DEST}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
